---
- name: start click
  hosts: _click
  order: sorted
  become: yes
  tasks:
  - name: make sure services are enabled and started
    systemd:
      name: "zookeeper"
      daemon-reload: yes
      enabled: yes
      state: started