---
- import_playbook: roles/install-docker.yml
- name: Add docker
  hosts: all
  become: yes
  tasks:
  - name: Create a data container
    docker_container:
      name: mydata
      image: busybox
      volumes:
        - /data