---
- hosts: _kuber:&_master
  become: yes
  gather_facts: false
  tasks:
    - name: set join command
      set_fact:
        join_command: "aaaaaaaaaaaaaaaaa"

- hosts: _kuber:&_worker
  become: yes
  tasks:
    - name: test
      set_fact:
        kubernetes_master_dns: "{{ groups['_kuber']| intersect(groups['_master']) }}"
    - name: test1
      debug: 
        msg: "{{kubernetes_master_dns[0]}}"
    - name: set join command
      debug: 
        msg: "{{hostvars[kubernetes_master_dns[0]].join_command}}"