---
- hosts: all
  become: yes
  tasks:
  - name: Print all available facts
    debug:
      var: groups
- hosts: all
  tasks:
  - name: Gather facts from new server
    setup:
      filter: hostvars[{{ item }}]
    loop: groups['all']

  - name: Gather facts from db servers
    setup:
    delegate_to: "{{ item }}"
    delegate_facts: true
    loop: "{{ groups['all'] }}"