---
- name: ec2 facts
  order: sorted
  hosts: _click
  become: yes
  tasks:
  - name: Add zookeeper variable
    lineinfile:
      dest: "/opt/slam/.clickhouse.env"
      line: "ZOO{{index}}={{dns}}"
    with_indexed_items:
      - "{{ groups['_zoo'] }}"
    vars:
      index: "{{item.0}}"
      dns: "{{hostvars[item.1]['ansible_fqdn']}}"

