# Ansible playbook AWS - install docker (2021)
---
- name: "AWS - Install docker"
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: install docker
      shell: "amazon-linux-extras install docker"

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes
