---
- name: initialise ec2
  hosts: all
  become: yes
  tasks:
  - name: Install a list of packages
    apt:
      pkg:
      - apt-transport-https 
      - ca-certificates 
      - dirmngr
      state: present

  - name: Add clickhouse repository to apk repo
    lineinfile:
      dest: "/etc/apt/sources.list.d/clickhouse.list"
      line: "deb https://repo.clickhouse.tech/deb/stable/ main/"
      create: yes

  - name: Add GPG key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: E0C56BD4

  - name: Update all packages
    apt:
      name: "*"
      state: present
      update_cache: yes

  - name: install clickhouse
    apt:
      name: clickhouse-server=21.7.7.47
      state: present

  - name: copy config.xml
    copy:
      src: config.xml
      dest: /etc/clickhouse-server/config.xml
      owner: root
      mode: '0644'
      
  - name: make sure services are enabled and started
    systemd:
      name: clickhouse-server
      daemon-reload: yes
      enabled: yes
      state: started