---
- hosts: _kuber:&_master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
    - debug:
        msg: "{{ hostvars[inventory_hostname].join_command }}"

- hosts: _kuber:&_worker
  become: yes
  tasks:
    - name: get dns of kubernetes and master intersect
      set_fact:
        kubernetes_master_dns: "{{ groups['_kuber']| intersect(groups['_master']) }}"
    - name: join cluster
      shell: "{{ hostvars[kubernetes_master_dns[0]].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt